---
name: Build Project
on:
  - push
concurrency:
  group: "builds"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install esbuild globally
        run: |
          esbuild_version=$(npm list esbuild | grep esbuild | cut -d '@' -f 2)
          npm install -g esbuild@${esbuild_version}
      - name: Build
        run: ./bin/build build
      - name: Verify Build
        run: ./bin/build test-build
