---
name: Run Tests
on:
  - push
concurrency:
  group: "tests"
  cancel-in-progress: false
jobs:
  lts-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/-2', 'lts/-1']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  current-runtime:
    runs-on: ubuntu-latest
    needs: lts-runtime
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test-coverage
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ./bin/build build
      - name: Verify Build
        run: |
          file .aws-sam/build/Dependencies/nodejs/node_modules/@img/sharp-libvips-linux-x64/lib/libvips-cpp.so.* | grep 'ELF 64-bit LSB shared object, x86-64' >/dev/null
          file .aws-sam/build/Dependencies/nodejs/node_modules/@img/sharp-linux-x64/lib/sharp-linux-x64.node | grep 'ELF 64-bit LSB shared object, x86-64' >/dev/null
          file .aws-sam/build/Dependencies/lib/libvips-cpp.so | grep 'ELF 64-bit LSB shared object, x86-64' >/dev/null
          test -e .aws-sam/build/IiifFunction/index.js
