---
name: Run Tests
on:
  - push
concurrency:
  group: "tests"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jdx/mise-action@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test-coverage
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
